python bert_lstm_ner.py   \
     --task_name="NER"  \ 
     --do_train=True   \
     --do_eval=True   \
     --do_predict=True
     --data_dir=/home/lef/Desktop/   \
     --vocab_file=/home/lef/Desktop/bert_chinese/vocab.txt  \ 
     --bert_config_file=/home/lef/Desktop/bert_chinese/bert_config.json \  
     --init_checkpoint=/home/lef/Desktop/bert_chinese/bert_model.ckpt   \
     --max_seq_length=128   \
     --train_batch_size=32   \
     --learning_rate=2e-5   \
     --num_train_epochs=3.0   \
     --output_dir=/home/lef/Desktop/output/ 
